#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> [subdomain]

# Function to get subdomain information
domain_information () {
    local domain="$1"
    local subdomain="$2"
    local line
    # shellcheck disable=SC2086
    line=$(dig "$subdomain"."$domain" +short)
    if [ -z "$line" ]; then
        echo "The subdomain $subdomain does not exist."
    else
        echo "$subdomain A $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    fi
}

# Check if the domain is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Main logic to display subdomain information
if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi