#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

./1-install_nginx_web_server
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/MohamedAlaga permanent;' /etc/nginx/sites-available/default
service nginx reload
