#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" | sudo tee  /var/www/html/index.html.
echo "Ceci n'est pas une page." | sudo tee /var/www/html/custom_404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/MohamedAlaga;
    error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html/;
                internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart