#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures an Nginx server so that with costum header 

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/MohamedAlaga permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By "375502-web-02";' /etc/nginx/sites-available/default
service nginx start
