#!/usr/bin/env bash
#configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo '
frontend mohamedalaga.tech
        bind 0:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 35.175.132.56:80 check
        server web2 54.157.130.43.104:80 check
' >> sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
