#!/usr/bin/env bash
# enable only ports 22/80/443
sudo ufw reset --force
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
yes | sudo ufw enable
